Assignment 11
lkrawczykowski/webdev-fundamentals pull request #4
Opened 2017-04-24 14:20 UTC by lkrawczykowski

2017-04-25 05:52 UTC, Reshetnyak requested changes

2017-04-25 05:52 UTC, Reshetnyak commented on 11/client/src/javascripts/app.js
> +                replacement.href = element.getAttribute("href");
Please, see my comments for task 10 pull request. The same can be improved here.

2017-04-25 05:52 UTC, Reshetnyak commented on 11/client/src/javascripts/wd.js
> +                console.error(url + " is not defined");
Please, avoid such constructions. You wouldn't be able to use debugger or set a breakpoint in the body of `if`

2017-04-25 05:52 UTC, Reshetnyak commented on 11/client/src/javascripts/wd.js
> +            this.components.push({ name: name, descriptor: descriptor });
You are using ES2015 and can leverage [object properties shorthands](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer)
```javacript
this.components.push({ name, descriptor });
```

2017-04-26 08:37 UTC, lkrawczykowski commented on 11/client/src/javascripts/wd.js
> +                console.error(url + " is not defined");
I am not sure what you mean, lack of brackets?

2017-04-26 09:44 UTC, Reshetnyak commented on 11/client/src/javascripts/wd.js
> +                console.error(url + " is not defined");
Exactly. I would use examples next time to not confuse you.

2017-04-26 10:27 UTC, merged